name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy server
        uses: appleboy/ssh-action@master
        env:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
        with:
          script: |
            cd /home/envans/apps/server-colyseus
            git checkout develop
            git pull
            echo 'LATEST CHANGES PULLED'
