name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  copy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@master
      - name: copy files
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_KEY }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: '.,!node_modules'
          target: '~/apps/server-colyseus/'

  deploy:
    needs: copy
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: appleboy/ssh-action@master
        with:
          script: |
            cd /home/envans/apps/server-colyseus
            docker ps -aq | xargs docker stop | xargs docker rm
            docker rmi envans/colyseus
            docker build -t envans/colyseus .
            docker run -d -p 8080:8080 --restart unless-stopped envans/colyseus
            echo 'LATEST CHANGES PULLED'
        env:
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_KEY }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
