name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-lastest
    environment: main
    steps:
      - name: copy file via ssh password
      - uses: actions/checkout@v2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/apps/server-colyseus/"
      - name: Make docker
      - uses: appleboy/ssh-action@master
      with:
        script: |
          cd /home/envans/apps/server-colyseus
          docker ps -aq | xargs docker stop | xargs docker rm
          docker rmi envans/colyseus
          docker build -t envans/colyseus .
          docker run -d -p 8080:8080 --restart unless-stopped envans/colyseus
          echo 'LATEST CHANGES PULLED'
      env:
        HOST: ${{ secrets.SSH_HOST }}
        KEY: ${{ secrets.SSH_KEY }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        FINGERPRINT: ${{ secrets.SSH_FINGER }}
