name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_KEY }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /home/envans/apps/server-colyseus
            git checkout develop
            git pull
            echo 'LATEST CHANGES PULLED'
