name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v2
      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd /home/envans/apps/server-colyseus
            git checkout main
            git pull origin main
            echo $PASSPHRASE
            docker ps -aq | xargs docker stop | xargs docker rm
            docker rmi envans/colyseus
            docker build -t envans/colyseus .
            docker run -d -p 8080:8080 --restart unless-stopped envans/colyseus
            echo 'LATEST CHANGES PULLED'
        env:
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_KEY }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
