name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@master
      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: '.,!node_modules'
          target: '~/app/gobarber-backend'
        env:
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_KEY }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          FINGERPRINT: ${{ secrets.SSH_FINGER }}
